import { test, expect } from '@playwright/test';
import { feature } from '../../server/demo.ts';
const ready = async (page: any) => { await page.goto('/?time=all&points=4096&autoload=1'); await page.waitForFunction(() => (window as any).__WFS_MAP__?.metrics.analysisCharts?.length === 3); for (const toggle of await page.getByRole('button', { name: 'Settings', exact: true }).all()) await toggle.click(); };
test('configuration is a subpage and navigation retains selection and chart state', async ({ page }) => {
    await ready(page);
    await expect(page.locator('#url')).toBeHidden();
    await expect(page.locator('.chart-card')).toHaveCount(3);
    await page.locator('#configLink').click();
    await expect(page.locator('#url')).toBeHidden();
    await page.getByRole('button', { name: 'Configure WFS source', exact: true }).click();
    await expect(page.locator('#url')).toBeVisible();
    await page.locator('#cancelSource').click();
    await expect(page.locator('#analysis')).toBeHidden();
    await page.locator('#analysisLink').click();
    await expect(page.locator('.chart-card')).toHaveCount(3);
    await expect(page.locator('#filterStatus')).toContainText('4,096 matches');
});
test('chart clicks cross-filter all charts, OR selections combine, and removing a condition restores the dataset', async ({ page }) => {
    await ready(page);
    const first = page.locator('.chart-card').first();
    await first.locator('details summary').click();
    await first.getByRole('button', { name: 'category: sensor · 1,024', exact: true }).click();
    await expect(page.locator('#filterStatus')).toContainText('1,024 matches');
    await page.locator('#rules > .filter-group > .group-head > select').selectOption('or');
    await page.locator('#apply').click();
    await expect(page.locator('#filterStatus')).toContainText('1,024 matches');
    await first.getByRole('button', { name: 'category: vehicle · 0', exact: true }).click();
    await expect(page.locator('#filterStatus')).toContainText('2,048 matches');
    const counts = await page.evaluate(() => (window as any).__WFS_MAP__.workspace.results.map((r: any) => r.counts.reduce((a: number, b: number) => a + b, 0) + r.missing));
    expect(counts).toEqual([2048, 2048, 2048]);
    await page.locator('#reset').click();
    await expect(page.locator('#filterStatus')).toContainText('4,096 matches');
});
test('all chart types configure from schema and scatter drag produces an exact AND range', async ({ page }) => {
    await ready(page);
    const first = page.locator('.chart-card').first();
    await first.getByLabel('Chart type').selectOption('pie');
    await page.waitForFunction(() => (window as any).__WFS_MAP__.workspace.results[0].type === 'pie');
    const canvas = first.locator('canvas'), box = (await canvas.boundingBox())!;
    await page.mouse.click(box.x + box.width / 2 + 60, box.y + 120);
    await expect(page.locator('#filterStatus')).toContainText('1,024 matches');
    await page.locator('#reset').click();
    await expect(page.locator('#filterStatus')).toContainText('4,096 matches');
    const scatter = page.locator('.chart-card').nth(2);
    await scatter.getByLabel('Binning', { exact: true }).selectOption('8');
    await page.waitForFunction(() => (window as any).__WFS_MAP__.workspace.results[2].counts.length === 64);
    await scatter.locator('canvas').scrollIntoViewIfNeeded();
    const b = (await scatter.locator('canvas').boundingBox())!, dx = (b.width - 86) / 8, dy = (b.height - 82) / 8;
    await page.mouse.move(b.x + 68 + dx * .5, b.y + b.height - 64 - dy * .5);
    await page.mouse.down({ button: 'right' });
    await page.mouse.move(b.x + 68 + dx * 2.5, b.y + b.height - 64 - dy * 2.5);
    await page.mouse.up({ button: 'right' });
    await page.waitForFunction(() => document.getElementById('filterStatus')?.textContent?.includes('matches'));
    const result = await page.evaluate(() => (window as any).__WFS_MAP__.workspace.results[2]);
    const bounds = await page.evaluate(() => { const r = (window as any).__WFS_MAP__.workspace.results[2]; return { x: r.x.ranges.slice(0, 4), y: r.y.ranges.slice(0, 4), xf: r.x.field, yf: r.y.field, count: (window as any).__WFS_MAP__.metrics.filterCount }; });
    const expected = Array.from({ length: 4096 }, (_, i) => feature(i)).filter(f => { const p = f.properties as any; return p[bounds.xf] >= bounds.x[0] && p[bounds.xf] < bounds.x[3] && p[bounds.yf] >= bounds.y[0] && p[bounds.yf] < bounds.y[3]; }).length;
    expect(bounds.count).toBe(expected);
    expect(result.type).toBe('scatter');
});
test('nested manual filters, latest request wins, empty result and keyboard selection', async ({ page }) => {
    await ready(page);
    await page.locator('#rules > .filter-group > .group-head').getByRole('button', { name: '+ Group', exact: true }).click();
    const group = page.locator('#rules .filter-group .filter-group');
    await group.getByRole('button', { name: '+ Rule', exact: true }).click();
    await group.getByLabel('Attribute').selectOption('value');
    await group.getByLabel('Operator').selectOption('gte');
    await group.getByLabel('Filter value').fill('50');
    await page.locator('#apply').click();
    const n = Array.from({ length: 4096 }, (_, i) => feature(i)).filter(f => f.properties.value >= 50).length;
    await expect(page.locator('#filterStatus')).toContainText(`${n.toLocaleString()} matches`);
    await page.evaluate(() => { const h = (window as any).__WFS_MAP__; h.filter([{ field: 'id', op: 'eq', value: '1' }]); h.filter([{ field: 'id', op: 'eq', value: '-1' }]); });
    await expect(page.locator('#filterStatus')).toContainText('0 matches');
    await page.locator('#reset').click();
    await expect(page.locator('#filterStatus')).toContainText('4,096 matches');
    await page.locator('.chart-card').first().locator('canvas').focus();
    await page.keyboard.press('Enter');
    await expect(page.locator('#filterStatus')).toContainText('1,024 matches');
});
