import { navigate, openFilters } from '../navigation.ts';
import { test, expect } from '@playwright/test';
import { emptyState } from '../../src/analysis-state.ts';

test('Independent Log10 axes, fitted filtering, brush membership, enlargement and reload', async ({ page }) => {
    const errors: string[] = []; page.on('pageerror', e => errors.push(e.message));
    const doc = { id: 'scales', name: 'Scale test', revision: 1, updatedAt: new Date().toISOString(), readOnly: false, shared: false, state: emptyState() };
    doc.state.query = { choice: 'all', bounds: {} };
    await page.route('**/api/**', async route => {
        const request = route.request(), path = new URL(request.url()).pathname;
        if (path === '/api/me') return route.fulfill({ json: { user: 'analyst' } });
        if (path !== '/api/analyses/scales') return route.continue();
        if (request.method() === 'PUT') { doc.state = request.postDataJSON().state; doc.revision++; }
        await route.fulfill({ json: doc });
    });
    await page.goto('/?analysis=scales#configuration'); await page.locator('#addSource').click();
    await page.locator('#sourceName').fill('Log axes'); await page.locator('#type').selectOption('csv');
    await page.locator('#csvFile').setInputFiles({ name: 'axes.csv', mimeType: 'text/csv', buffer: Buffer.from('lon,lat,x,y,code\n-1,54,1,1,A\n-1,54,10,10,B\n-1,54,100,100,C\n-1,54,1000,1000,D\n-1,54,0,-1,Z') });
    await page.locator('#updateSource').click(); await page.locator('#saveSettings').click();
    await page.waitForFunction(() => (window as any).__WFS_MAP__?.sources[0]?.metrics.analysisCharts?.length);
    await navigate(page, 'analysis');
    const chart = page.locator('.chart-card').filter({ has: page.getByRole('heading', { name: 'Scatter plot', exact: true }) });
    await chart.getByRole('button', { name: 'Settings', exact: true }).click();
    await chart.getByLabel('X attribute', { exact: true }).selectOption('x');
    await chart.getByLabel('Y attribute', { exact: true }).selectOption('y');
    await chart.getByLabel('Binning', { exact: true }).selectOption('exact');
    await chart.getByLabel('X axis scale', { exact: true }).selectOption('log10');
    await chart.getByLabel('Y axis scale', { exact: true }).selectOption('log10');
    const plot = chart.locator('.raw-scatter > canvas').first();
    await expect(plot).toHaveAttribute('data-scale-x', 'log10'); await expect(plot).toHaveAttribute('data-scale-y', 'log10');
    await expect(chart).toContainText('4 plotted · 1 missing');
    const readView = () => plot.getAttribute('data-view').then(v => JSON.parse(v!));
    const initial = await readView();
    await openFilters(page);
    await page.locator('#rules > .filter-group > .group-head').getByRole('button', { name: '+ Rule', exact: true }).click();
    await page.getByLabel('Attribute', { exact: true }).selectOption('x'); await page.getByLabel('Operator').selectOption('lte');
    await page.getByLabel('Filter value').fill('10'); await page.locator('#apply').click();
    await expect(chart).toContainText('2 plotted');
    const filtered = await readView(); expect(filtered[2] - filtered[0]).toBeLessThan((initial[2] - initial[0]) / 2);
    await plot.scrollIntoViewIfNeeded();
    const box = (await plot.boundingBox())!;
    await page.mouse.move(box.x + 85, box.y + 30); await page.mouse.down();
    await page.mouse.move(box.x + box.width - 35, box.y + box.height - 80); await page.mouse.up();
    const zoomed = await readView(); expect(zoomed[2] - zoomed[0]).toBeLessThan(filtered[2] - filtered[0]);
    await chart.getByRole('button', { name: 'Fit data', exact: true }).click(); expect(await readView()).toEqual(filtered);
    await chart.getByRole('button', { name: 'Enlarge', exact: true }).click();
    await expect(page.locator('.chart-dialog')).toBeVisible();
    await expect(plot).toHaveAttribute('data-scale-x', 'log10');
    const plotBox = (await plot.boundingBox())!, timelineBox = (await page.locator('.chart-dialog > .timeline').boundingBox())!;
    expect(plotBox.y + plotBox.height).toBeLessThanOrEqual(timelineBox.y);
    await page.screenshot({ path: '/tmp/wfs-chart-log-axes.png' });
    await page.keyboard.press('Escape');
    // Select the full fitted rectangle: values are converted back from log space.
    await plot.scrollIntoViewIfNeeded();
    const b = (await plot.boundingBox())!;
    await page.mouse.move(b.x + 69, b.y + 19); await page.mouse.down({ button: 'right' });
    await page.mouse.move(b.x + b.width - 19, b.y + b.height - 65); await page.mouse.up({ button: 'right' });
    await page.locator('#apply').click(); await expect(page.locator('#filterStatus')).toContainText('2 matches');
    await navigate(page, 'configuration');
    await page.getByRole('button', { name: 'Save analysis', exact: true }).click();
    await expect(page.locator('.saved-analysis-bar')).toContainText('Analysis configuration saved');
    await page.reload(); await page.waitForFunction(() => (window as any).__WFS_MAP__?.sources[0]?.done);
    await navigate(page, 'analysis');
    await expect(page.locator('.raw-scatter > canvas').first()).toHaveAttribute('data-scale-x', 'log10');
    expect(errors).toEqual([]);
});

test('Logarithmic count and aggregate Y axes keep positive bounds and date/category axes linear', async ({ page }) => {
    const errors: string[] = []; page.on('pageerror', e => errors.push(e.message));
    await page.goto('/?time=all#configuration'); await page.locator('#addSource').click();
    await page.locator('#sourceName').fill('Measures'); await page.locator('#type').selectOption('csv');
    await page.locator('#csvFile').setInputFiles({ name: 'measures.csv', mimeType: 'text/csv', buffer: Buffer.from('lon,lat,t,value,code\n-1,54,2026-10-01,1,A\n-1,54,2026-10-02,10,B\n-1,54,2026-10-03,100,B\n-1,54,2026-10-04,-1,B\n-1,54,2026-10-05,0,B') });
    await page.locator('#csvTime').selectOption('t'); await page.locator('#updateSource').click(); await page.locator('#saveSettings').click();
    await page.waitForFunction(() => (window as any).__WFS_MAP__?.sources[0]?.metrics.analysisCharts?.length);
    await navigate(page, 'analysis');
    const bar = page.locator('.chart-card').filter({ has: page.getByRole('heading', { name: 'Bar chart', exact: true }) });
    await bar.getByRole('button', { name: 'Settings', exact: true }).click();
    await expect(bar.getByLabel('X axis scale', { exact: true })).toBeDisabled();
    await bar.getByLabel('Y axis scale', { exact: true }).selectOption('log10');
    await expect(bar.locator('canvas')).toHaveAttribute('data-scale-y', 'log10');
    let bounds = JSON.parse((await bar.locator('canvas').getAttribute('data-bounds'))!);
    expect(bounds[1]).toBeGreaterThan(0); expect(bounds[3]).toBeGreaterThan(4);
    const time = page.locator('.chart-card').filter({ has: page.getByRole('heading', { name: 'Time series', exact: true }) });
    await time.getByRole('button', { name: 'Settings', exact: true }).click();
    await expect(time.getByLabel('X axis scale', { exact: true })).toBeDisabled();
    await time.getByLabel('Y aggregation', { exact: true }).selectOption('mean');
    await time.getByLabel('Y attribute', { exact: true }).selectOption('value');
    await time.getByLabel('Y axis scale', { exact: true }).selectOption('log10');
    await expect(time.locator('canvas')).toHaveAttribute('data-scale-y', 'log10');
    bounds = JSON.parse((await time.locator('canvas').getAttribute('data-bounds'))!);
    expect(bounds[1]).toBeGreaterThan(0); expect(bounds[3]).toBeGreaterThan(100);
    await expect(time).toContainText('Log10 omits non-positive values');
    expect(errors).toEqual([]);
});
