import { test, expect } from '@playwright/test';
import { defaultConfig } from '../../src/source-settings.ts';
async function seed(page:any){await page.addInitScript((config:any)=>localStorage.setItem('wfs-settings',JSON.stringify({sources:[{id:'a',name:'Celsius',enabled:true,config:{...config,type:'csv',timeField:'when',longitudeField:'lon',latitudeField:'lat',csvText:'lon,lat,asset,when,celsius\n0,0,A,2026-10-01T00:00:00Z,0\n1,1,B,2026-10-01T01:00:00Z,10\n2,2,C,2026-10-01T02:00:00Z,20'}},{id:'b',name:'Fahrenheit',enabled:true,config:{...config,type:'csv',timeField:'observed',longitudeField:'lon',latitudeField:'lat',csvText:'lon,lat,station,observed,fahrenheit\n0.0001,0,A,2026-10-01T00:00:30Z,32\n0.0002,0,A,2026-10-01T00:00:45Z,50\n1,1,B,2026-10-01T01:02:00Z,50\n2,2,X,2026-10-01T02:00:00Z,68'}}]})),defaultConfig);}
test('comparison UI maps fields and conversions, shares buckets, and relationships preview ambiguity with explicit propagation',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await seed(page);await page.goto('/?time=all#analysis');await page.waitForFunction(()=>(window as any).__WFS_MAP__?.sources.every((s:any)=>s.done&&!s.filtering));
 const panel=page.locator('#comparisonPanel');await panel.getByLabel('Comparison name',{exact:true}).fill('Temperatures');await panel.getByLabel('Common measure unit',{exact:true}).fill('C');
 const series=panel.locator('.comparison-series');await series.nth(0).getByLabel('Mapped X field',{exact:true}).selectOption('celsius');await series.nth(0).getByLabel('Series measure unit',{exact:true}).fill('C');await series.nth(1).getByLabel('Mapped X field',{exact:true}).selectOption('fahrenheit');await series.nth(1).getByLabel('Series measure unit',{exact:true}).fill('F');
 await panel.getByRole('button',{name:'Create comparison',exact:true}).click();await expect(panel.locator('form [role=status]')).toContainText('explicit conversion');
 await series.nth(1).getByLabel('Convert explicitly:',{exact:false}).check();await series.nth(1).getByLabel('Conversion scale',{exact:true}).fill(String(5/9));await series.nth(1).getByLabel('Conversion offset',{exact:true}).fill(String(-32*5/9));
 await panel.getByRole('button',{name:'Create comparison',exact:true}).click();await expect(panel.locator('.comparison-card [role=status]')).toContainText('24 common bins');await expect(panel.locator('.comparison-legend')).toContainText('3 plotted');await expect(panel.locator('.comparison-legend')).toContainText('4 plotted');
 await panel.locator('.comparison-card').getByRole('button',{name:'Edit',exact:true}).click();await panel.getByLabel('Comparison type',{exact:true}).selectOption('time');await series.nth(0).getByLabel('Mapped X field',{exact:true}).selectOption('when');await series.nth(1).getByLabel('Mapped X field',{exact:true}).selectOption('observed');await series.nth(0).getByLabel('Mapped measure field',{exact:true}).selectOption('celsius');await series.nth(1).getByLabel('Mapped measure field',{exact:true}).selectOption('fahrenheit');await panel.getByRole('button',{name:'Update comparison',exact:true}).click();await expect(panel.locator('.comparison-card [role=status]')).toContainText('3 common UTC buckets');
 await page.locator('#recordsLink').click();const relationships=page.locator('#relationshipPanel');await relationships.getByLabel('Left identifier',{exact:true}).selectOption('asset');await relationships.getByLabel('Right identifier',{exact:true}).selectOption('station');await relationships.getByLabel('Match UTC time within tolerance',{exact:true}).check();await relationships.getByLabel('Left timestamp',{exact:true}).selectOption('when');await relationships.getByLabel('Right timestamp',{exact:true}).selectOption('observed');await relationships.getByLabel('Time tolerance (seconds)',{exact:true}).fill('45');await relationships.getByLabel('Match geographic proximity',{exact:true}).check();await relationships.getByLabel('Radius (metres, great-circle distance)',{exact:true}).fill('50');await relationships.getByRole('button',{name:'Save relationship and preview',exact:true}).click();await expect(relationships.locator('.comparison-card [role=status]')).toContainText('1/3 matched');await expect(relationships.locator('.comparison-card [role=status]')).toContainText('1 multiply matched candidates');
 await page.locator('.record-row').first().click();await expect(relationships.getByRole('button',{name:'Inspect related records:',exact:false})).toBeVisible();await relationships.getByRole('button',{name:'Inspect related records:',exact:false}).click();await expect(page.getByRole('dialog',{name:'Choose overlapping record'})).toBeVisible();await expect(page.locator('.record-choices button')).toHaveCount(2);await page.locator('.record-choices button').last().click();await expect(page.locator('.record-inspector')).toContainText('Fahrenheit');expect(await page.evaluate(()=>(window as any).__WFS_MAP__.sources.map((s:any)=>s.selected))).toEqual([3,4]);
 await page.reload();await expect(relationships.locator('.comparison-card [role=status]')).toContainText('1/3 matched');await page.locator('#analysisLink').click();await expect(panel.locator('.comparison-card [role=status]')).toContainText('3 common UTC buckets');
 // A changed applied filter invalidates and recalculates both features.
 await page.evaluate(()=>(window as any).__WFS_MAP__.filterSource('a',[{field:'asset',op:'eq',value:'B'}]));await expect(panel.locator('.comparison-legend')).toContainText('1 plotted');await page.locator('#recordsLink').click();await expect(relationships.locator('.comparison-card [role=status]')).toContainText('0/1 matched');
 expect(errors).toEqual([]);
});

test('saved comparison and relationship specs round-trip without uploading records or match results',async({page,context})=>{
 const makeSeries=(id:string,sourceId:string)=>({id,sourceId,label:sourceId,x:'value',unit:'dimensionless',scale:1,offset:0,converted:false,filter:{op:'and',children:[]}});
 let doc:any={id:'linked',name:'Linked analysis',revision:1,updatedAt:new Date().toISOString(),readOnly:false,shared:false,state:{schemaVersion:1,settings:{sources:['a','b'].map((id,i)=>({id,name:id,enabled:true,config:{...defaultConfig,url:`http://127.0.0.1:8787/wfs?points=${i?11:7}`,layer:'demo:points'}})),background:{url:'',attribution:'',enabled:false}},query:{choice:'all',bounds:{}},analyses:[],comparisons:[{id:'comparison',name:'Saved values',kind:'histogram',unit:'dimensionless',bins:8,bucketMs:3600000,aggregate:'count',series:[makeSeries('s1','a'),makeSeries('s2','b')]}],relationships:[{id:'relation',name:'Same identifier',leftSource:'a',rightSource:'b',identifier:{left:'id',right:'id'},match:'unique'}]}};
 const payloads:string[]=[];
 await context.route('**/api/**',async route=>{const path=new URL(route.request().url()).pathname;const method=route.request().method();if(path==='/api/me')return route.fulfill({json:{user:'analyst'}});if(path==='/api/analyses/linked'){if(method==='PUT'){payloads.push(route.request().postData()!);const body=route.request().postDataJSON();doc={...doc,state:body.state,revision:doc.revision+1};}return route.fulfill({json:doc});}return route.fulfill({status:404,json:{error:'unknown'}});});
 await page.goto('/?analysis=linked#analysis');await expect(page.locator('#comparisonPanel .comparison-card [role=status]')).toContainText('8 common bins');await page.getByRole('button',{name:'Save analysis',exact:true}).click();await expect(page.locator('.saved-analysis-bar')).toContainText('configuration saved');
 expect(payloads).toHaveLength(1);const payload=JSON.parse(payloads[0]);expect(payload.state.comparisons[0].series).toHaveLength(2);expect(payload.state.relationships[0].identifier).toEqual({left:'id',right:'id'});for(const forbidden of ['"csvText"','"coordinates"','"members"','"pairs"','"preview"','"results"','"indices"'])expect(payloads[0]).not.toContain(forbidden);
 await page.reload();await expect(page.locator('#comparisonPanel .comparison-card [role=status]')).toContainText('8 common bins');await page.locator('#recordsLink').click();await expect(page.locator('#relationshipPanel .comparison-card [role=status]')).toContainText('7/7 matched');
});
