import { test, expect } from '@playwright/test';
import { feature } from '../../server/demo.ts';
const ready = async (page: any) => { await page.goto('/?time=all&points=4096&autoload=1'); await page.waitForFunction(() => (window as any).__WFS_MAP__?.workspace.results.length === 3); for (const toggle of await page.getByRole('button', { name: 'Settings', exact: true }).all()) await toggle.click(); };
test('every chart collapses all settings while keeping enlargement and removal available', async ({ page }) => {
    await page.goto('/?time=all&points=4096&autoload=1');
    await page.waitForFunction(() => (window as any).__WFS_MAP__?.workspace.results.length === 3);
    const cards = page.locator('.chart-card');
    for (const card of await cards.all()) {
        await expect(card.getByRole('button', { name: 'Settings', exact: true })).toHaveAttribute('aria-expanded', 'false');
        await expect(card.getByLabel('Chart type')).toBeHidden();
        await expect(card.getByRole('button', { name: 'Enlarge', exact: true })).toBeVisible();
        await expect(card.getByRole('button', { name: 'Remove chart' })).toBeVisible();
    }
    const card = cards.first(), toggle = card.getByRole('button', { name: 'Settings', exact: true });
    for (const type of ['bar', 'pie', 'time', 'scatter']) {
        await toggle.focus();
        await page.keyboard.press('Enter');
        await expect(toggle).toHaveAttribute('aria-expanded', 'true');
        await card.getByLabel('Chart type').selectOption(type);
        await page.waitForFunction(t => (window as any).__WFS_MAP__.workspace.results[0].type === t, type);
        const before = await page.evaluate(() => ({ specs: (window as any).__WFS_MAP__.workspace.specs, filters: (window as any).__WFS_MAP__.sources[0].filterRequest }));
        await toggle.click();
        await expect(card.locator('.chart-controls')).toBeHidden();
        await expect(card.getByRole('heading')).toHaveText({ bar: 'Bar chart', pie: 'Pie chart', time: 'Time series', scatter: 'Scatter plot' }[type]!);
        await card.getByRole('button', { name: 'Enlarge', exact: true }).click();
        await expect(page.getByRole('dialog').locator('.chart-controls')).toBeHidden();
        await page.getByRole('dialog').getByRole('button', { name: 'Settings', exact: true }).click();
        await expect(page.getByRole('dialog').getByLabel('Chart type')).toHaveValue(type);
        await page.keyboard.press('Escape');
        await expect(card.getByLabel('Chart type')).toBeVisible();
        await toggle.click();
        const after = await page.evaluate(() => ({ specs: (window as any).__WFS_MAP__.workspace.specs, filters: (window as any).__WFS_MAP__.sources[0].filterRequest }));
        expect(after).toEqual(before);
    }
    await card.getByRole('button', { name: 'Remove chart' }).click();
    await expect(cards).toHaveCount(2);
});
test('labeled chart settings expose only relevant controls and use one scatter binning dropdown', async ({ page }) => {
    await ready(page);
    const bar = page.locator('.chart-card').first(), time = page.locator('.chart-card').nth(1), scatter = page.locator('.chart-card').nth(2);
    await expect(bar.getByLabel('Group by', { exact: true })).toHaveValue('category');
    await expect(bar.getByLabel('Binning', { exact: true })).toBeHidden();
    await bar.getByLabel('Group by', { exact: true }).selectOption('value');
    await expect(bar.getByLabel('Binning', { exact: true })).toBeVisible();
    await expect(bar.getByLabel('Binning', { exact: true }).locator('option[value=exact]')).toHaveCount(0);
    await bar.getByLabel('Binning', { exact: true }).selectOption('8');
    await page.waitForFunction(() => (window as any).__WFS_MAP__.workspace.results[0].x.ranges?.length === 9);
    await expect(time.getByLabel('Time attribute', { exact: true })).toHaveValue('timestamp');
    await expect(time.getByLabel('Y attribute', { exact: true })).toBeHidden();
    await time.getByLabel('Y aggregation').selectOption('mean');
    await expect(time.getByLabel('Y attribute', { exact: true })).toBeVisible();
    await time.getByLabel('Y aggregation').selectOption('count');
    await expect(time.getByLabel('Y attribute', { exact: true })).toBeHidden();
    await expect(time.locator('.chart-field').filter({ hasText: 'Y attribute' })).toBeHidden();
    await expect(scatter.locator('.chart-controls select:visible')).toHaveCount(8);
    await expect(scatter.getByLabel('X axis scale', { exact: true })).toBeEnabled();
    await expect(scatter.getByLabel('Y axis scale', { exact: true })).toBeEnabled();
    const binning = scatter.getByLabel('Binning', { exact: true });
    await expect(binning.locator('option[value=exact]')).toHaveText('No bins — individual points');
    await binning.selectOption('exact');
    await expect(binning).toBeEnabled();
    await page.waitForFunction(() => (window as any).__WFS_MAP__.workspace.results[2].raw?.rows.length === 4096);
    await binning.selectOption('16');
    await page.waitForFunction(() => { const r = (window as any).__WFS_MAP__.workspace.results[2]; return !r.raw && r.x.ranges.length === 17 && r.y.ranges.length === 17; });
    await expect(scatter.locator('.raw-scatter')).toHaveCount(0);
    // Labels and descriptions remain associated after axis/type changes and at narrow widths.
    for (const width of [1440, 820, 375]) {
        await page.setViewportSize({ width, height: 900 });
        const controls = await page.locator('.chart-card select:visible').evaluateAll(selects => selects.map(select => {
            const s = select as HTMLSelectElement, rect = s.getBoundingClientRect(), card = s.closest('.chart-card')!.getBoundingClientRect();
            return { label: s.labels?.[0]?.textContent, described: !!document.getElementById(s.getAttribute('aria-describedby')!), fits: rect.left >= card.left && rect.right <= card.right };
        }));
        expect(controls.every(c => c.label && c.described && c.fits)).toBe(true);
    }
});
test('basemap template and attribution persist and use local tiles', async ({ page }) => {
    const requests: string[] = [];
    await page.route('**/tiles/**', route => { requests.push(route.request().url()); return route.fulfill({ status: 200, contentType: 'image/png', body: Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAAC0lEQVR4nGNgAAIAAAUAAXpeqz8AAAAASUVORK5CYII=', 'base64') }); });
    await ready(page);
    await page.locator('#configLink').click();
    await page.locator('#backgroundSettings summary').click();
    await page.getByLabel('Raster basemap tile URL').fill('/tiles/{z}/{x}/{y}.png');
    await page.getByLabel('Raster basemap tile URL').press('Tab');
    await page.getByLabel('Basemap attribution', { exact: true }).fill('Local tiles');
    await page.getByLabel('Basemap attribution', { exact: true }).press('Tab');
    await page.locator('#saveSettings').click();
    await page.locator('#analysisLink').click();
    await page.locator('#basemap').check();
    await expect.poll(() => requests.length).toBeGreaterThan(0);
    const tiles = await page.evaluate(() => (window as any).__WFS_MAP__.map.getStyle().sources.osm.tiles);
    expect(tiles).toEqual(['/tiles/{z}/{x}/{y}.png']);
    await page.reload();
    await page.waitForFunction(() => (window as any).__WFS_MAP__?.workspace.results.length === 3);
    await page.locator('#configLink').click();
    await page.locator('#backgroundSettings summary').click();
    await expect(page.getByLabel('Raster basemap tile URL')).toHaveValue('/tiles/{z}/{x}/{y}.png');
    await expect(page.getByLabel('Basemap attribution', { exact: true })).toHaveValue('Local tiles');
    await page.getByLabel('Raster basemap tile URL').fill('javascript:bad');
    await page.locator('#saveSettings').click();
    await page.getByLabel('Raster basemap tile URL').press('Tab');
    await expect(page.getByLabel('Raster basemap tile URL')).toHaveAttribute('aria-invalid', 'true');
});
test('time Y mean and scatter mode are configurable; raw scatter clicks select one original observation', async ({ page }) => {
    await ready(page);
    const time = page.locator('.chart-card').nth(1);
    await time.getByLabel('Y aggregation').selectOption('mean');
    await time.getByLabel('Y attribute').selectOption('quality');
    await page.waitForFunction(() => (window as any).__WFS_MAP__.workspace.results[1].measure === 'mean(quality)');
    const aggregate = await page.evaluate(() => { const r = (window as any).__WFS_MAP__.workspace.results[1]; return { counts: [...r.counts], values: [...r.values], ranges: [...r.x.ranges] }; });
    for (let i = 0; i < aggregate.counts.length; i++) {
        const rows = Array.from({ length: 4096 }, (_, j) => feature(j)).filter(f => { const x = Date.parse(f.properties.timestamp as string); return x >= aggregate.ranges[i] && (i === aggregate.counts.length - 1 ? x <= aggregate.ranges[i + 1] : x < aggregate.ranges[i + 1]); });
        expect(aggregate.values[i]).toBeCloseTo(rows.reduce((s, f) => s + Number(f.properties.quality), 0) / rows.length, 8);
    }
    const bar = page.locator('.chart-card').first();
    await expect(bar.getByLabel('Binning', { exact: true })).toBeHidden();
    await bar.getByLabel('Chart type').selectOption('pie');
    await page.waitForFunction(() => (window as any).__WFS_MAP__.workspace.results[0].type === 'pie');
    await expect(time.getByLabel('Binning', { exact: true }).locator('option[value=exact]')).toHaveCount(0);
    const scatter = page.locator('.chart-card').nth(2);
    await scatter.getByLabel('Binning', { exact: true }).selectOption('exact');
    await page.waitForFunction(() => (window as any).__WFS_MAP__.workspace.results[2].raw?.rows.length === 4096);
    const canvas = scatter.locator('.raw-scatter canvas:not(.raw-scatter-axes)');
    await canvas.scrollIntoViewIfNeeded();
    const b = (await canvas.boundingBox())!;
    const pos = await page.evaluate(() => Array.from((window as any).__WFS_MAP__.workspace.results[2].raw.positions.slice(0, 2)) as number[]);
    await page.mouse.click(b.x + 68 + (b.width - 86) * (pos[0] + 1) / 2, b.y + b.height - 64 - (b.height - 82) * (pos[1] + 1) / 2);
    await expect(page.locator('#filterStatus')).toContainText('1 matches');
    await expect(page.locator('#rules')).toContainText('Observation');
    await page.locator('#reset').click();
    await expect(page.locator('#filterStatus')).toContainText('4,096 matches');
    await canvas.scrollIntoViewIfNeeded();
    const box = (await canvas.boundingBox())!;
    await page.mouse.move(box.x + 68 + (box.width - 86) * .2, box.y + 18 + (box.height - 82) * .25);
    await page.mouse.down({ button: 'right' });
    await page.mouse.move(box.x + 68 + (box.width - 86) * .7, box.y + 18 + (box.height - 82) * .8);
    await page.mouse.up({ button: 'right' });
    await expect(page.locator('#rules .selection .rule')).toHaveCount(4);
    const e = await page.evaluate(() => (window as any).__WFS_MAP__.workspace.expression());
    const rules = e.children[0].children;
    const expected = Array.from({ length: 4096 }, (_, j) => feature(j)).filter(f => rules.every((r: any) => r.op === 'gte' ? Number(f.properties[r.field]) >= Number(r.value) : Number(f.properties[r.field]) <= Number(r.value))).length;
    await expect(page.locator('#filterStatus')).toContainText(`${expected.toLocaleString()} matches`);
});
test('right-drag map box matches geographic bounds and point colours keep IDs and compact buffers', async ({ page }) => {
    await ready(page);
    await page.getByLabel('Point colour attribute').selectOption('value');
    await page.waitForFunction(() => (window as any).__WFS_MAP__.layer.colorCodes?.length === 4096);
    const colors = await page.evaluate(() => { const l = (window as any).__WFS_MAP__.layer; return { codes: Array.from(l.colorCodes) as number[], bytes: l.colorCodes.byteLength, palette: Array.from(l.palette), error: l.gl.getError() }; });
    expect(colors.bytes).toBe(4096);
    expect(colors.error).toBe(0);
    expect(new Set(colors.codes).size).toBe(24);
    expect(colors.palette[0]).not.toBe(colors.palette[69]);
    const canvas = page.locator('#map canvas'); await canvas.scrollIntoViewIfNeeded(); const b = (await canvas.boundingBox())!;
    await page.mouse.move(b.x + b.width * .25, b.y + b.height * .25);
    await page.mouse.down({ button: 'right' });
    await page.mouse.move(b.x + b.width * .65, b.y + b.height * .7, { steps: 5 });
    await expect(page.locator('.geo-box')).toBeVisible();
    await page.mouse.up({ button: 'right' });
    await expect(page.locator('.geo-box')).toBeHidden();
    await expect(page.locator('#areaSummary')).toContainText('Map area:');
    await page.waitForFunction(() => (window as any).__WFS_MAP__.done);
    const bounds = await page.evaluate(() => (window as any).__WFS_MAP__.queryBounds.bbox);
    const expected = Array.from({ length: 4096 }, (_, i) => feature(i)).filter(f => { const [x, y] = f.geometry.coordinates; return x >= bounds.west && x <= bounds.east && y >= bounds.south && y <= bounds.north; }).length;
    await expect(page.locator('#filterStatus')).toContainText(`${expected.toLocaleString()} matches`);
    expect(expected).toBeGreaterThan(0);
    expect(expected).toBeLessThan(4096);
    await page.getByLabel('Low value colour').fill('#ff0000');
    await page.waitForFunction(() => (window as any).__WFS_MAP__.layer.palette[0] === 1);
    await page.getByLabel('Point colour attribute').selectOption('');
    await page.waitForFunction(() => !(window as any).__WFS_MAP__.layer.colorCodes);
    await expect(page.locator('#filterStatus')).toContainText(`${expected.toLocaleString()} matches`);
});
test('sources retain independent colour attributes and geographic selections across switching and reload', async ({ page }) => {
    await ready(page);
    await page.getByLabel('Point colour attribute').selectOption('quality');
    await page.waitForFunction(() => (window as any).__WFS_MAP__.layer.colorCodes?.length === 4096);
    await page.locator('.chart-card').nth(2).getByLabel('Binning', { exact: true }).selectOption('exact');
    await page.waitForFunction(() => (window as any).__WFS_MAP__.workspace.results[2].raw);
    await page.locator('#configLink').click();
    await page.locator('#addSource').click();
    await page.locator('#sourceName').fill('Other');
    await page.locator('#url').fill('/wfs?points=1024');
    await page.locator('#layer').fill('demo:points');
    await page.locator('#updateSource').click();
    await page.locator('#saveSettings').click();
    await page.waitForFunction(() => (window as any).__WFS_MAP__.sources[1].workspace.results.length === 3);
    await page.locator('#analysisLink').click();
    const ids = await page.evaluate(() => (window as any).__WFS_MAP__.sources.map((s: any) => s.id));
    await page.locator('#filterSource').selectOption(ids[1]); await page.locator('#colorSource').selectOption(ids[1]);
    await expect(page.getByLabel('Point colour attribute')).toHaveValue('');
    await page.getByLabel('Point colour attribute').selectOption('value');
    await page.waitForFunction(() => (window as any).__WFS_MAP__.layer.colorCodes?.length === 1024);
    await page.evaluate(() => { const h = (window as any).__WFS_MAP__; h.workspace.select({ op: 'bbox', west: -5, east: 0, south: 52, north: 56 }, 'Other box'); });
    await page.waitForFunction(() => !(window as any).__WFS_MAP__.sources[1].workspace.results.some((r: any) => r.counts.reduce((a: number, b: number) => a + b, 0) + r.missing !== (window as any).__WFS_MAP__.sources[1].selected));
    await page.locator('#filterSource').selectOption(ids[0]); await page.locator('#colorSource').selectOption(ids[0]);
    await expect(page.getByLabel('Point colour attribute')).toHaveValue('quality');
    await expect(page.locator('#rules .rule')).toHaveCount(0);
    await expect(page.locator('.raw-scatter canvas:not(.raw-scatter-axes)')).toHaveCount(1);
    expect(await page.evaluate(() => (window as any).__WFS_MAP__.sources[0].selected)).toBe(4096);
    await page.locator('#filterSource').selectOption(ids[1]); await page.locator('#colorSource').selectOption(ids[1]);
    await expect(page.getByLabel('Point colour attribute')).toHaveValue('value');
    await expect(page.locator('#rules .rule').getByLabel('Attribute')).toHaveValue('bbox');
    await expect(page.locator('#rules .rule').getByLabel('Filter value')).toHaveValue('W -5, S 52, E 0, N 56');
    await page.reload();
    await page.waitForFunction(() => (window as any).__WFS_MAP__?.sources.every((s: any) => s.done && s.layer.colorCodes));
    await expect(page.getByLabel('Point colour attribute')).toHaveValue('quality');
    await page.locator('#filterSource').selectOption(ids[1]); await page.locator('#colorSource').selectOption(ids[1]);
    await expect(page.getByLabel('Point colour attribute')).toHaveValue('value');
});
