import { test, expect } from '@playwright/test';
import { feature } from '../../server/demo.ts';
const ready = async (page: any) => { await page.goto('/?points=4096&autoload=1'); await page.waitForFunction(() => (window as any).__WFS_MAP__?.workspace.results.length === 3); };
test('basemap template and attribution persist and use local tiles', async ({ page }) => {
    const requests: string[] = [];
    await page.route('**/tiles/**', route => { requests.push(route.request().url()); return route.fulfill({ status: 200, contentType: 'image/png', body: Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jRZkAAAAASUVORK5CYII=', 'base64') }); });
    await ready(page);
    await page.locator('#configLink').click();
    await page.getByLabel('Raster basemap tile URL').fill('/tiles/{z}/{x}/{y}.png');
    await page.getByLabel('Raster basemap tile URL').press('Tab');
    await page.getByLabel('Basemap attribution', { exact: true }).fill('Local tiles');
    await page.getByLabel('Basemap attribution', { exact: true }).press('Tab');
    await page.locator('#analysisLink').click();
    await page.locator('#basemap').check();
    await expect.poll(() => requests.length).toBeGreaterThan(0);
    const tiles = await page.evaluate(() => (window as any).__WFS_MAP__.map.getStyle().sources.osm.tiles);
    expect(tiles).toEqual(['/tiles/{z}/{x}/{y}.png']);
    await page.reload();
    await page.waitForFunction(() => (window as any).__WFS_MAP__?.workspace.results.length === 3);
    await page.locator('#configLink').click();
    await expect(page.getByLabel('Raster basemap tile URL')).toHaveValue('/tiles/{z}/{x}/{y}.png');
    await expect(page.getByLabel('Basemap attribution', { exact: true })).toHaveValue('Local tiles');
    await page.getByLabel('Raster basemap tile URL').fill('javascript:bad');
    await page.getByLabel('Raster basemap tile URL').press('Tab');
    await expect(page.getByLabel('Raster basemap tile URL')).toHaveAttribute('aria-invalid', 'true');
});
test('time Y mean and scatter mode are configurable; raw scatter clicks select one original observation', async ({ page }) => {
    await ready(page);
    const time = page.locator('.chart-card').nth(1);
    await time.getByLabel('Y aggregation').selectOption('mean');
    await time.getByLabel('Y attribute').selectOption('quality');
    await page.waitForFunction(() => (window as any).__WFS_MAP__.workspace.results[1].measure === 'mean(quality)');
    const aggregate = await page.evaluate(() => { const r = (window as any).__WFS_MAP__.workspace.results[1]; return { counts: [...r.counts], values: [...r.values], ranges: [...r.x.ranges] }; });
    for (let i = 0; i < aggregate.counts.length; i++) {
        const rows = Array.from({ length: 4096 }, (_, j) => feature(j)).filter(f => { const x = Date.parse(f.properties.timestamp as string); return x >= aggregate.ranges[i] && (i === aggregate.counts.length - 1 ? x <= aggregate.ranges[i + 1] : x < aggregate.ranges[i + 1]); });
        expect(aggregate.values[i]).toBeCloseTo(rows.reduce((s, f) => s + Number(f.properties.quality), 0) / rows.length, 8);
    }
    const bar = page.locator('.chart-card').first();
    await expect(bar.getByLabel('Binning', { exact: true })).toBeHidden();
    await bar.getByLabel('Chart type').selectOption('pie');
    await page.waitForFunction(() => (window as any).__WFS_MAP__.workspace.results[0].type === 'pie');
    await expect(time.getByLabel('Binning', { exact: true })).toBeHidden();
    const scatter = page.locator('.chart-card').nth(2);
    await scatter.getByLabel('Binning', { exact: true }).selectOption('exact');
    await page.waitForFunction(() => (window as any).__WFS_MAP__.workspace.results[2].raw?.rows.length === 4096);
    const canvas = scatter.locator('.raw-scatter canvas:not(.raw-scatter-axes)');
    await canvas.scrollIntoViewIfNeeded();
    const b = (await canvas.boundingBox())!;
    const pos = await page.evaluate(() => Array.from((window as any).__WFS_MAP__.workspace.results[2].raw.positions.slice(0, 2)) as number[]);
    await page.mouse.click(b.x + 68 + (b.width - 86) * (pos[0] + 1) / 2, b.y + b.height - 64 - (b.height - 82) * (pos[1] + 1) / 2);
    await expect(page.locator('#filterStatus')).toContainText('1 matches');
    await expect(page.locator('#rules')).toContainText('Observation');
    await page.locator('#reset').click();
    await expect(page.locator('#filterStatus')).toContainText('4,096 matches');
    await canvas.scrollIntoViewIfNeeded();
    const box = (await canvas.boundingBox())!;
    await page.mouse.move(box.x + 68 + (box.width - 86) * .2, box.y + 18 + (box.height - 82) * .25);
    await page.mouse.down({ button: 'right' });
    await page.mouse.move(box.x + 68 + (box.width - 86) * .7, box.y + 18 + (box.height - 82) * .8);
    await page.mouse.up({ button: 'right' });
    await expect(page.locator('#rules')).toContainText('rectangle');
    const e = await page.evaluate(() => (window as any).__WFS_MAP__.workspace.expression());
    const rules = e.children[0].children;
    const expected = Array.from({ length: 4096 }, (_, j) => feature(j)).filter(f => rules.every((r: any) => r.op === 'gte' ? Number(f.properties[r.field]) >= Number(r.value) : Number(f.properties[r.field]) <= Number(r.value))).length;
    await expect(page.locator('#filterStatus')).toContainText(`${expected.toLocaleString()} matches`);
});
test('right-drag map box matches geographic bounds and point colours keep IDs and compact buffers', async ({ page }) => {
    await ready(page);
    await page.getByLabel('Point colour attribute').selectOption('value');
    await page.waitForFunction(() => (window as any).__WFS_MAP__.layer.colorCodes?.length === 4096);
    const colors = await page.evaluate(() => { const l = (window as any).__WFS_MAP__.layer; return { codes: Array.from(l.colorCodes) as number[], bytes: l.colorCodes.byteLength, palette: Array.from(l.palette), error: l.gl.getError() }; });
    expect(colors.bytes).toBe(4096);
    expect(colors.error).toBe(0);
    expect(new Set(colors.codes).size).toBe(24);
    expect(colors.palette[0]).not.toBe(colors.palette[69]);
    const canvas = page.locator('#map canvas'), b = (await canvas.boundingBox())!;
    await page.mouse.move(b.x + b.width * .25, b.y + b.height * .25);
    await page.mouse.down({ button: 'right' });
    await page.mouse.move(b.x + b.width * .65, b.y + b.height * .7, { steps: 5 });
    await expect(page.locator('.geo-box')).toBeVisible();
    await page.mouse.up({ button: 'right' });
    await expect(page.locator('.geo-box')).toBeHidden();
    await expect(page.locator('#rules')).toContainText('Map box:');
    const bounds = await page.evaluate(() => (window as any).__WFS_MAP__.workspace.expression().children[0]);
    const expected = Array.from({ length: 4096 }, (_, i) => feature(i)).filter(f => { const [x, y] = f.geometry.coordinates; return x >= bounds.west && x <= bounds.east && y >= bounds.south && y <= bounds.north; }).length;
    await expect(page.locator('#filterStatus')).toContainText(`${expected.toLocaleString()} matches`);
    expect(expected).toBeGreaterThan(0);
    expect(expected).toBeLessThan(4096);
    await page.getByLabel('Low value colour').fill('#ff0000');
    await page.waitForFunction(() => (window as any).__WFS_MAP__.layer.palette[0] === 1);
    await page.getByLabel('Point colour attribute').selectOption('');
    await page.waitForFunction(() => !(window as any).__WFS_MAP__.layer.colorCodes);
    await expect(page.locator('#filterStatus')).toContainText(`${expected.toLocaleString()} matches`);
});
test('sources retain independent colour attributes and geographic selections across switching and reload', async ({ page }) => {
    await ready(page);
    await page.getByLabel('Point colour attribute').selectOption('quality');
    await page.waitForFunction(() => (window as any).__WFS_MAP__.layer.colorCodes?.length === 4096);
    await page.locator('.chart-card').nth(2).getByLabel('Binning', { exact: true }).selectOption('exact');
    await page.waitForFunction(() => (window as any).__WFS_MAP__.workspace.results[2].raw);
    await page.locator('#configLink').click();
    await page.locator('#addSource').click();
    await page.locator('#sourceName').fill('Other');
    await page.locator('#points').fill('1024');
    await page.locator('#sourceName').blur();
    await page.getByRole('checkbox', { name: 'Enable Other', exact: true }).check();
    await page.waitForFunction(() => (window as any).__WFS_MAP__.sources[1].workspace.results.length === 3);
    await page.locator('#analysisLink').click();
    const ids = await page.evaluate(() => (window as any).__WFS_MAP__.sources.map((s: any) => s.id));
    await page.locator('#analysisSource').selectOption(ids[1]);
    await expect(page.getByLabel('Point colour attribute')).toHaveValue('');
    await page.getByLabel('Point colour attribute').selectOption('value');
    await page.waitForFunction(() => (window as any).__WFS_MAP__.layer.colorCodes?.length === 1024);
    await page.evaluate(() => { const h = (window as any).__WFS_MAP__; h.workspace.select({ op: 'bbox', west: -5, east: 0, south: 52, north: 56 }, 'Other box'); });
    await page.waitForFunction(() => !(window as any).__WFS_MAP__.sources[1].workspace.results.some((r: any) => r.counts.reduce((a: number, b: number) => a + b, 0) + r.missing !== (window as any).__WFS_MAP__.sources[1].selected));
    await page.locator('#analysisSource').selectOption(ids[0]);
    await expect(page.getByLabel('Point colour attribute')).toHaveValue('quality');
    await expect(page.locator('#rules')).not.toContainText('Other box');
    await expect(page.locator('.raw-scatter canvas:not(.raw-scatter-axes)')).toHaveCount(1);
    expect(await page.evaluate(() => (window as any).__WFS_MAP__.sources[0].selected)).toBe(4096);
    await page.locator('#analysisSource').selectOption(ids[1]);
    await expect(page.getByLabel('Point colour attribute')).toHaveValue('value');
    await expect(page.locator('#rules')).toContainText('Other box');
    await page.reload();
    await page.waitForFunction(() => (window as any).__WFS_MAP__?.sources.every((s: any) => s.done && s.layer.colorCodes));
    await expect(page.getByLabel('Point colour attribute')).toHaveValue('quality');
    await page.locator('#analysisSource').selectOption(ids[1]);
    await expect(page.getByLabel('Point colour attribute')).toHaveValue('value');
});
