import { navigate, openFilters } from '../navigation.ts';
import { test, expect } from '@playwright/test';
test('CSV imports alongside WFS, configures fields, filters, colours, and persists its file', async ({ page }) => {
    const errors: string[] = []; page.on('pageerror', e => errors.push(e.message));
    await page.goto('/?time=all&points=16&autoload=1');
    await page.waitForFunction(() => (window as any).__WFS_MAP__?.done);
    await navigate(page, 'configuration'); await page.locator('#addSource').click();
    await page.getByLabel('Source name', { exact: true }).fill('CSV stations');
    await page.getByLabel('Source type').selectOption('csv');
    await expect(page.locator('#url')).toBeHidden();
    await page.getByLabel('CSV file', { exact: true }).setInputFiles({ name: 'stations.csv', mimeType: 'text/csv', buffer: Buffer.from('lon,lat,observed,temp,station\n-1,54,2026-10-01T00:00:00Z,7,north\n-2,53,2026-10-02T00:00:00Z,9,south') });
    await expect(page.locator('#csvFileStatus')).toContainText('5 columns');
    await page.locator('#csvTime').selectOption('observed');
    await page.locator('#updateSource').click(); await page.locator('#saveSettings').click();
    await page.waitForFunction(() => (window as any).__WFS_MAP__?.sources[1]?.metrics.analysisCharts?.length);
    await navigate(page, 'analysis');
    await expect(page.locator('#hud')).toHaveText('Loaded 18 points');
    const id = await page.evaluate(() => (window as any).__WFS_MAP__.sources[1].id);
    await openFilters(page);
    await page.locator('#filterSource').selectOption(id);
    await page.locator('#rules > .filter-group > .group-head').getByRole('button', { name: '+ Rule', exact: true }).click();
    await page.getByLabel('Attribute', { exact: true }).selectOption('temp');
    await page.getByLabel('Operator').selectOption('gte'); await page.getByLabel('Filter value').fill('8'); await page.locator('#apply').click();
    await expect(page.locator('#filterStatus')).toContainText('1 matches');
    await page.locator('#colorSource').selectOption(id); await page.locator('#colorAttribute').selectOption('temp'); await expect(page.locator('#colorLegend')).toContainText('7');
    await page.evaluate(() => (window as any).__WFS_MAP__.getPoint(0));
    await expect(page.locator('.metadata')).toContainText('CSV stations'); await expect(page.locator('.metadata')).toContainText('north');
    await page.reload(); await page.waitForFunction(() => (window as any).__WFS_MAP__?.sources.every((s: any) => s.done));
    await expect(page.locator('#hud')).toHaveText('Loaded 18 points');
    await navigate(page, 'configuration'); await page.getByRole('button', { name: 'Configure CSV stations', exact: true }).click();
    await expect(page.locator('#type')).toHaveValue('csv'); await expect(page.locator('#csvTime')).toHaveValue('observed'); await expect(page.locator('#csvFileStatus')).toContainText('stations.csv');
    await page.locator('#cancelSource').click(); await navigate(page, 'analysis');
    await openFilters(page);
    await page.locator('#timeWindow').selectOption('custom'); await page.locator('#timeStart').fill('2026-10-02T00:00'); await page.locator('#timeEnd').fill('2026-10-03T00:00'); await page.locator('#applyTime').click();
    await page.waitForFunction(() => (window as any).__WFS_MAP__?.sources[1]?.done && (window as any).__WFS_MAP__?.sources[1].loaded === 1);
    expect(errors).toEqual([]);
});
test('CSV validates files and supports a configured WKT geometry column', async ({ page }) => {
    await page.goto('/?time=all#configuration'); await page.locator('#addSource').click(); await page.locator('#sourceName').fill('WKT'); await page.locator('#type').selectOption('csv');
    await page.locator('#csvFile').setInputFiles({ name: 'bad.csv', mimeType: 'text/csv', buffer: Buffer.from('a,a\n1,2') });
    await expect(page.locator('#sourceError')).toContainText('unique');
    await page.locator('#csvFile').setInputFiles({ name: 'points.csv', mimeType: 'text/csv', buffer: Buffer.from('geom,value\nPOINT (-1 54),2') });
    await expect(page.locator('#csvFileStatus')).toContainText('2 columns'); await page.locator('#geometryMode').selectOption('wkt');
    await expect(page.locator('#csvXY')).toBeHidden(); await page.locator('#csvGeometry').selectOption('geom');
    await page.locator('#updateSource').click(); await page.locator('#saveSettings').click(); await page.waitForFunction(() => (window as any).__WFS_MAP__?.sources[0]?.done);
    await navigate(page, 'analysis'); await expect(page.locator('#hud')).toHaveText('Loaded 1 points');
});

test('CSV import skips invalid rows, reports reasons and retains valid records and null metadata', async ({ page }) => {
    const errors: string[] = []; page.on('pageerror', e => errors.push(e.message));
    await page.goto('/?time=all#configuration'); await page.locator('#addSource').click();
    await page.locator('#sourceName').fill('Mixed CSV'); await page.locator('#type').selectOption('csv');
    await page.locator('#csvFile').setInputFiles({ name: 'mixed.csv', mimeType: 'text/csv', buffer: Buffer.from('lon,lat,t,note\n-1,54,2026-10-01,"first\nsecond"\n,54,2026-10-01,missing\n-1,54,bad,time\n-1,54\n-2,53,,') });
    await expect(page.locator('#csvFileStatus')).toContainText('Rows are validated during import');
    await page.locator('#csvTime').selectOption('t');
    await page.locator('#updateSource').click(); await page.locator('#saveSettings').click();
    await page.waitForFunction(() => (window as any).__WFS_MAP__?.sources[0]?.done);
    await navigate(page, 'analysis');
    await expect(page.locator('#hud')).toHaveText('Loaded 2 points');
    const source = await page.evaluate(() => (window as any).__WFS_MAP__.sources[0]);
    expect(source.metrics.csvReport).toMatchObject({ total: 5, imported: 2, rejected: 3, filtered: 0 });
    expect(source.status).toContain('3 rows not processed'); expect(source.status).toContain('CSV line 4');
    expect(source.status).toContain('Missing longitude'); expect(source.status).toContain('Invalid ISO 8601');
    await expect(page.locator('#status')).toContainText('3 rows not processed');
    await navigate(page, 'records');
    await expect(page.locator('.record-row')).toHaveCount(2);
    await navigate(page, 'analysis');
    await page.evaluate(() => (window as any).__WFS_MAP__.getPoint(1));
    await expect(page.locator('.metadata')).toContainText('csv.7');
    await page.reload(); await page.waitForFunction(() => (window as any).__WFS_MAP__?.sources[0]?.done);
    expect(await page.evaluate(() => (window as any).__WFS_MAP__.sources[0].metrics.csvReport.rejected)).toBe(3);
    expect(errors).toEqual([]);
});

test('CSV with all blank times or headers only loads safely without timeline or page errors', async ({ page }) => {
    const errors: string[] = []; page.on('pageerror', e => errors.push(e.message));
    await page.goto('/?time=all#configuration'); await page.locator('#addSource').click();
    await page.locator('#sourceName').fill('Blank times'); await page.locator('#type').selectOption('csv');
    await page.locator('#csvFile').setInputFiles({ name: 'blank.csv', mimeType: 'text/csv', buffer: Buffer.from('lon,lat,t,empty\n-1,54,,\n-2,53,,') });
    await page.locator('#csvTime').selectOption('t');
    await page.locator('#updateSource').click(); await page.locator('#saveSettings').click();
    await page.waitForFunction(() => (window as any).__WFS_MAP__?.sources[0]?.done);
    expect(await page.evaluate(() => (window as any).__WFS_MAP__.sources[0].loaded)).toBe(2);
    await navigate(page, 'analysis');
    await expect(page.getByLabel('Use time window')).toBeDisabled();
    await navigate(page, 'configuration'); await page.getByRole('button', { name: 'Configure Blank times', exact: true }).click();
    await page.locator('#csvFile').setInputFiles({ name: 'empty.csv', mimeType: 'text/csv', buffer: Buffer.from('lon,lat,t,empty') });
    await page.locator('#updateSource').click(); await page.locator('#saveSettings').click();
    await page.waitForFunction(() => (window as any).__WFS_MAP__?.sources[0]?.done && (window as any).__WFS_MAP__.sources[0].loaded === 0);
    expect(errors).toEqual([]);
});

test('CSV rejects all invalid rows with complete counts and no misleading partial-load claim', async ({ page }) => {
    const errors: string[] = []; page.on('pageerror', e => errors.push(e.message));
    await page.goto('/?time=all#configuration'); await page.locator('#addSource').click();
    await page.locator('#sourceName').fill('Invalid'); await page.locator('#type').selectOption('csv');
    await page.locator('#csvFile').setInputFiles({ name: 'invalid.csv', mimeType: 'text/csv', buffer: Buffer.from('lon,lat\n,54\n-1,\nno,54') });
    await page.locator('#updateSource').click(); await page.locator('#saveSettings').click();
    await page.waitForFunction(() => (window as any).__WFS_MAP__?.sources[0]?.error);
    await navigate(page, 'analysis');
    await expect(page.locator('#status')).toContainText('0 of 3');
    await expect(page.locator('#status')).toContainText('3 rows not processed');
    await expect(page.locator('#status')).toContainText('No points were imported');
    await expect(page.locator('#status')).not.toContainText('Partial points are visible');
    expect(errors).toEqual([]);
});

test('CSV column type override makes numeric codes categorical and survives reload and reconfiguration', async ({ page }) => {
    await page.goto('/?time=all#configuration'); await page.locator('#addSource').click();
    await page.locator('#sourceName').fill('Codes'); await page.locator('#type').selectOption('csv');
    await page.locator('#csvFile').setInputFiles({ name: 'codes.csv', mimeType: 'text/csv', buffer: Buffer.from('lon,lat,code,value\n-1,54,001,1\n-2,53,002,100') });
    await page.locator('#csvTypes summary').click();
    await page.getByLabel('Type for code', { exact: true }).selectOption('string');
    await page.locator('#updateSource').click(); await page.locator('#saveSettings').click();
    await page.waitForFunction(() => (window as any).__WFS_MAP__?.sources[0]?.done);
    await navigate(page, 'analysis');
    await page.locator('#colorAttribute').selectOption('code');
    await expect(page.locator('#categoryColorCount')).toContainText('2 of 2');
    await expect(page.getByLabel('Colour for 001', { exact: true })).toBeVisible();
    await page.reload(); await page.waitForFunction(() => (window as any).__WFS_MAP__?.sources[0]?.done);
    await navigate(page, 'configuration'); await page.getByRole('button', { name: 'Configure Codes', exact: true }).click();
    await expect(page.getByLabel('Type for code', { exact: true })).toHaveValue('string');
});

test('local map area filters CSV without importing again and newly added WFS sources inherit it', async ({ page }) => {
  await page.goto('/?time=all#configuration'); await page.locator('#addSource').click();
  await page.locator('#sourceName').fill('Map CSV'); await page.locator('#type').selectOption('csv');
  await page.locator('#csvFile').setInputFiles({ name: 'map.csv', mimeType: 'text/csv', buffer: Buffer.from('lon,lat,value\n-3,54,7\n-3,54,9\n0,52,10') });
  await page.locator('#updateSource').click(); await page.locator('#saveSettings').click();
  await page.waitForFunction(() => (window as any).__WFS_MAP__?.sources[0]?.done && !(window as any).__WFS_MAP__.sources[0].filtering);
  await navigate(page, 'analysis');
  await page.evaluate(() => (window as any).__WFS_MAP__.map.jumpTo({ center: [-3, 54], zoom: 7 }));
  const before = await page.evaluate(() => { const s = (window as any).__WFS_MAP__.sources[0]; return { request: s.request, report: s.metrics.csvReport }; });
  const canvas = page.locator('#map canvas'); const b = (await canvas.boundingBox())!;
  await page.mouse.move(b.x + b.width * .25, b.y + b.height * .25); await page.mouse.down({ button: 'right' });
  await page.mouse.move(b.x + b.width * .75, b.y + b.height * .75, { steps: 4 }); await page.mouse.up({ button: 'right' });
  await expect(page.locator('#filterStatus')).toContainText('2 matches');
  expect(await page.evaluate(() => { const s = (window as any).__WFS_MAP__.sources[0]; return { request: s.request, report: s.metrics.csvReport }; })).toEqual(before);
  await navigate(page, 'records'); await expect(page.locator('.record-row')).toHaveCount(2);
  await navigate(page, 'configuration'); await page.locator('#addSource').click();
  await page.locator('#sourceName').fill('Later WFS'); await page.locator('#url').fill('/wfs?points=4096'); await page.locator('#layer').fill('demo:points');
  await page.locator('#updateSource').click(); await page.locator('#saveSettings').click();
  await page.waitForFunction(() => (window as any).__WFS_MAP__.sources.length === 2 && (window as any).__WFS_MAP__.sources.every((s: any) => s.done && !s.filtering));
  expect(await page.evaluate(() => { const s = (window as any).__WFS_MAP__.sources[1]; return s.loaded === 4096 && s.selected < s.loaded; })).toBe(true);
  await navigate(page, 'analysis'); await openFilters(page); await page.locator('#clearLocalArea').click();
  await page.waitForFunction(() => (window as any).__WFS_MAP__.sources.every((s: any) => !s.filtering && s.selected === s.loaded));
});
