import { test, expect } from '@playwright/test';
test('CSV imports alongside WFS, configures fields, filters, colours, and persists its file', async ({ page }) => {
    const errors: string[] = []; page.on('pageerror', e => errors.push(e.message));
    await page.goto('/?time=all&points=16&autoload=1');
    await page.waitForFunction(() => (window as any).__WFS_MAP__?.done);
    await page.locator('#configLink').click(); await page.locator('#addSource').click();
    await page.getByLabel('Source name', { exact: true }).fill('CSV stations');
    await page.getByLabel('Source type').selectOption('csv');
    await expect(page.locator('#url')).toBeHidden();
    await page.getByLabel('CSV file', { exact: true }).setInputFiles({ name: 'stations.csv', mimeType: 'text/csv', buffer: Buffer.from('lon,lat,observed,temp,station\n-1,54,2026-10-01T00:00:00Z,7,north\n-2,53,2026-10-02T00:00:00Z,9,south') });
    await expect(page.locator('#csvFileStatus')).toContainText('5 columns');
    await page.locator('#csvTime').selectOption('observed');
    await page.locator('#updateSource').click(); await page.locator('#saveSettings').click();
    await page.waitForFunction(() => (window as any).__WFS_MAP__.sources[1]?.metrics.analysisCharts?.length);
    await page.locator('#analysisLink').click();
    await expect(page.locator('#hud')).toHaveText('Loaded 18 points');
    const id = await page.evaluate(() => (window as any).__WFS_MAP__.sources[1].id);
    await page.locator('#analysisSource').selectOption(id);
    await page.locator('#addRule').click();
    await page.getByLabel('Attribute', { exact: true }).selectOption('temp');
    await page.getByLabel('Operator').selectOption('gte'); await page.getByLabel('Filter value').fill('8'); await page.locator('#apply').click();
    await expect(page.locator('#filterStatus')).toContainText('1 matches');
    await page.locator('#colorAttribute').selectOption('temp'); await expect(page.locator('#colorLegend')).toContainText('7');
    await page.evaluate(() => (window as any).__WFS_MAP__.getPoint(0));
    await expect(page.locator('.metadata')).toContainText('CSV stations'); await expect(page.locator('.metadata')).toContainText('north');
    await page.reload(); await page.waitForFunction(() => (window as any).__WFS_MAP__.sources.every((s: any) => s.done));
    await expect(page.locator('#hud')).toHaveText('Loaded 18 points');
    await page.locator('#configLink').click(); await page.getByRole('button', { name: 'Configure CSV stations', exact: true }).click();
    await expect(page.locator('#type')).toHaveValue('csv'); await expect(page.locator('#csvTime')).toHaveValue('observed'); await expect(page.locator('#csvFileStatus')).toContainText('stations.csv');
    await page.locator('#cancelSource').click(); await page.locator('#analysisLink').click();
    await page.locator('#timeWindow').selectOption('custom'); await page.locator('#timeStart').fill('2026-10-02T00:00'); await page.locator('#timeEnd').fill('2026-10-03T00:00'); await page.locator('#applyTime').click();
    await page.waitForFunction(() => (window as any).__WFS_MAP__.sources[1]?.done && (window as any).__WFS_MAP__.sources[1].loaded === 1);
    expect(errors).toEqual([]);
});
test('CSV validates files and supports a configured WKT geometry column', async ({ page }) => {
    await page.goto('/?time=all#configuration'); await page.locator('#addSource').click(); await page.locator('#sourceName').fill('WKT'); await page.locator('#type').selectOption('csv');
    await page.locator('#csvFile').setInputFiles({ name: 'bad.csv', mimeType: 'text/csv', buffer: Buffer.from('a,a\n1,2') });
    await expect(page.locator('#sourceError')).toContainText('unique');
    await page.locator('#csvFile').setInputFiles({ name: 'points.csv', mimeType: 'text/csv', buffer: Buffer.from('geom,value\nPOINT (-1 54),2') });
    await expect(page.locator('#csvFileStatus')).toContainText('2 columns'); await page.locator('#geometryMode').selectOption('wkt');
    await expect(page.locator('#csvXY')).toBeHidden(); await page.locator('#csvGeometry').selectOption('geom');
    await page.locator('#updateSource').click(); await page.locator('#saveSettings').click(); await page.waitForFunction(() => (window as any).__WFS_MAP__.sources[0]?.done);
    await page.locator('#analysisLink').click(); await expect(page.locator('#hud')).toHaveText('Loaded 1 points');
});
