import { test, expect } from '@playwright/test';
import { categoryColors, colorBytes } from '../../src/category-colors.ts';

test('text colours are editable, stable, per-source and saved; gradients and solid colour show relevant controls', async ({ page }) => {
    const errors: string[] = []; page.on('pageerror', e => errors.push(e.message));
    await page.goto('/?time=all&points=64&autoload=1');
    await page.waitForFunction(() => (window as any).__WFS_MAP__?.done);
    await expect(page.locator('#sourceColor')).toBeVisible();
    await expect(page.locator('#colorLow')).toBeHidden();
    await page.locator('#colorAttribute').selectOption('category');
    await expect(page.locator('#colorLegend')).toContainText('4 unique values');
    await expect(page.locator('#sourceColor')).toBeHidden();
    await expect(page.locator('#colorBins')).toBeHidden();
    await expect(page.locator('#colorRamp')).toBeHidden();
    await expect(page.locator('#categoryColorList input')).toHaveCount(4);
    const rgb = await page.evaluate(() => { const l = (window as any).__WFS_MAP__.sources[0].layer; return { codes: Array.from(l.colorCodes), categorical: l.categorical, error: l.gl.getError() }; });
    expect(rgb.categorical).toBe(true); expect(rgb.codes.length).toBe(64 * 3); expect(rgb.error).toBe(0);
    expect(rgb.codes.slice(0, 3)).toEqual(colorBytes(categoryColors(['sensor','vehicle','station','event']).get('sensor')!));
    await page.getByLabel('Colour for sensor', { exact: true }).fill('#00ff00');
    await page.waitForFunction(() => { const l = (window as any).__WFS_MAP__.sources[0].layer; return l.colorCodes[0] === 0 && l.colorCodes[1] === 255 && l.colorCodes[2] === 0; });
    await page.locator('#addRule').click(); await page.getByLabel('Attribute', { exact: true }).selectOption('category');
    await page.getByLabel('Filter value', { exact: true }).fill('sensor'); await page.locator('#apply').click();
    await expect(page.locator('#filterStatus')).toContainText('16 matches');
    await expect(page.locator('#categoryColorList input')).toHaveCount(4);
    await page.reload(); await page.waitForFunction(() => (window as any).__WFS_MAP__?.done);
    await expect(page.getByLabel('Colour for sensor', { exact: true })).toHaveValue('#00ff00');
    await page.locator('#colorAttribute').selectOption('value');
    await page.waitForFunction(() => (window as any).__WFS_MAP__.sources[0].layer.colorCodes?.length === 64);
    await expect(page.locator('#categoryColors')).toBeHidden(); await expect(page.locator('#colorLow')).toBeVisible();
    await page.locator('#colorBins').selectOption('8'); await page.locator('#colorLow').fill('#ff0000');
    await page.waitForFunction(() => (window as any).__WFS_MAP__.sources[0].layer.palette[0] === 1);
    await page.locator('#colorAttribute').selectOption(''); await page.locator('#sourceColor').fill('#112233');
    await page.waitForFunction(() => !(window as any).__WFS_MAP__.sources[0].layer.colorCodes);
    await expect(page.locator('#colorLow')).toBeHidden();
    await page.locator('#colorAttribute').selectOption('category');
    await expect(page.getByLabel('Colour for sensor', { exact: true })).toHaveValue('#00ff00');
    await expect(page.locator('#colorAttribute option[value="timestamp"]')).toHaveCount(0);
    await expect(page.locator('#colorAttribute option[value="active"]')).toHaveCount(0);
    await page.locator('#configLink').click(); await page.locator('#addSource').click();
    await page.locator('#sourceName').fill('Second'); await page.locator('#url').fill('/wfs?points=16'); await page.locator('#layer').fill('demo:points');
    await page.locator('#updateSource').click(); await page.locator('#saveSettings').click();
    await page.waitForFunction(() => (window as any).__WFS_MAP__.sources[1]?.done);
    await page.locator('#analysisLink').click();
    const id = await page.evaluate(() => (window as any).__WFS_MAP__.sources[1].id);
    await page.locator('#colorSource').selectOption(id); await page.locator('#colorAttribute').selectOption('category');
    await expect(page.getByLabel('Colour for sensor', { exact: true })).toHaveValue(categoryColors(['sensor','vehicle','station','event']).get('sensor')!);
    const saved = await page.evaluate(() => JSON.parse(localStorage.getItem('wfs-settings')!).sources);
    expect(saved[0].coloring.categories.category.sensor).toBe('#00ff00'); expect(saved[1].coloring.categories).toBeUndefined();
    expect(errors).toEqual([]);
});

test('CSV categories are searchable and paged without an Other group or DOM cap on unique values', async ({ page }) => {
    await page.goto('/?time=all#configuration'); await page.locator('#addSource').click();
    await page.locator('#sourceName').fill('Many values'); await page.locator('#type').selectOption('csv');
    const csv = 'lon,lat,label\n' + Array.from({ length: 300 }, (_, i) => `-1,54,value-${i}`).join('\n');
    await page.getByLabel('CSV file', { exact: true }).setInputFiles({ name: 'many.csv', mimeType: 'text/csv', buffer: Buffer.from(csv) });
    await page.locator('#updateSource').click(); await page.locator('#saveSettings').click();
    await page.locator('#analysisLink').click(); await page.waitForFunction(() => (window as any).__WFS_MAP__?.done);
    await page.locator('#colorAttribute').selectOption('label');
    await expect(page.locator('#colorLegend')).toContainText('300 unique values');
    await expect(page.locator('#categoryColorList input')).toHaveCount(50);
    await page.locator('#moreCategoryColors').click(); await expect(page.locator('#categoryColorList input')).toHaveCount(100);
    await page.locator('#categorySearch').fill('value-299'); await expect(page.locator('#categoryColorList input')).toHaveCount(1);
    await page.getByLabel('Colour for value-299', { exact: true }).fill('#ff00ff');
    await page.waitForFunction(() => { const c = (window as any).__WFS_MAP__.sources[0].layer.colorCodes; return c?.length === 900 && c[897] === 255 && c[898] === 0 && c[899] === 255; });
    await expect(page.locator('#categorySearch')).toHaveValue('value-299');
    await page.setViewportSize({ width: 375, height: 812 }); await expect(page.locator('#categoryColorList')).toBeVisible();
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
});
