import { test, expect } from '@playwright/test';
import { defaultConfig } from '../../src/source-settings.ts';
test('Records is a third page, virtualizes applied results, searches, sorts, exports and inspects without filtering', async ({page})=>{
 const errors:string[]=[]; page.on('pageerror',e=>errors.push(e.message));
 await page.addInitScript(config=>localStorage.setItem('wfs-settings',JSON.stringify({sources:[{id:'a',name:'First',enabled:true,config:{...config,url:'/wfs?points=10000',layer:'demo:points'}},{id:'b',name:'Second',enabled:true,config:{...config,url:'/wfs?points=10',layer:'demo:points'}},{id:'c',name:'Disabled',enabled:false,config}]})),defaultConfig);
 await page.goto('/?time=all#records');
 await expect(page.locator('#records')).toBeVisible(); await expect(page.locator('#analysis')).toBeHidden();
 await expect(page.locator('#recordsSource option')).toHaveText(['First','Second']);
 await expect(page.locator('#records [role=status]')).toContainText('10,000 table rows');
 expect(await page.locator('.record-row').count()).toBeLessThanOrEqual(40);
 await page.locator('.record-row').first().click(); await expect(page.locator('.record-inspector')).toContainText('ID');
 expect(await page.evaluate(()=>(window as any).__WFS_MAP__.sources[0].selected)).toBe(10000);
 await page.getByLabel('Search applied records').fill('sensor'); await expect(page.locator('#records [role=status]')).toContainText('2,500 table rows');
 await page.getByRole('button',{name:'quality (number)',exact:true}).click();
 await page.locator('.records-scroll').focus(); await page.keyboard.press('End');
 await expect.poll(()=>page.locator('.record-row').first().getAttribute('aria-rowindex')).toMatch(/\d+/);
 const downloadPromise=page.waitForEvent('download'); await page.getByRole('button',{name:'Download table CSV'}).click(); const d=await downloadPromise; expect(d.suggestedFilename()).toBe('records.csv');
 await page.evaluate(()=>(window as any).__WFS_MAP__.chooseRecords([{sourceId:'a',index:0},{sourceId:'b',index:0}]));
 await expect(page.getByRole('dialog',{name:'Choose overlapping record'})).toBeVisible();
 await expect(page.locator('.record-choices')).toContainText('Second');
 await page.locator('.record-choices button').last().click(); await expect(page.locator('.record-inspector')).toContainText('Second');
 await page.locator('#analysisLink').click(); await expect(page.locator('.record-inspector')).toContainText('Second');
 await page.evaluate(()=>(window as any).__WFS_MAP__.filterSource('a',[{field:'quality',op:'gte',value:'90'}]));
 await page.locator('#recordsLink').click(); await expect(page.locator('#records [role=status]')).toContainText('applied matches');
 expect(errors).toEqual([]);
});
