import { openFilters } from '../navigation.ts';
import { test, expect, type Page } from '@playwright/test';
import { defaultConfig } from '../../src/source-settings.ts';
const ready = (page: Page) => page.waitForFunction(() => (window as any).__WFS_MAP__?.sources.every((s: any) => s.done && !s.loading && !s.filtering));
async function seed(page: Page, sources: any[]) {
    await page.addInitScript(sources => {
        if (!localStorage.getItem('wfs-settings')) localStorage.setItem('wfs-settings', JSON.stringify({ sources, background: { url: '', attribution: '', enabled: false } }));
    }, sources);
}
const wfs = (id: string) => ({ id, name: id, enabled: true, config: { ...defaultConfig, url: '/wfs?points=512&source=' + id, layer: 'demo:points', sort: 'id', pageSize: '31', limit: '2000' } });
test('collapsed per-source editor reloads only its WFS source, persists rules, and keeps dataset filters local', async ({ page }) => {
    await seed(page, [wfs('First'), wfs('Second')]);
    const requests: URL[] = [];
    page.on('request', r => { const url = new URL(r.url()); if (url.searchParams.get('request') === 'GetFeature') requests.push(url); });
    await page.goto('/?time=all&autoload=1'); await ready(page);
    await expect(page.locator('#advancedServerFilters')).not.toHaveAttribute('open');
    await expect(page.getByLabel('Server filter data source')).toBeHidden();
    await openFilters(page);
    await page.getByText('Advanced server filters', { exact: true }).click();
    await page.getByRole('button', { name: 'Add server rule', exact: true }).click();
    await page.getByLabel('Server rule 1 field', { exact: true }).selectOption('category');
    await page.getByLabel('Server rule 1 value', { exact: true }).fill('sensor');
    requests.length = 0;
    await page.getByRole('button', { name: 'Apply and reload source', exact: true }).click();
    await expect.poll(() => page.evaluate(() => (window as any).__WFS_MAP__.sources[0].loaded)).toBe(128); await ready(page);
    expect(await page.evaluate(() => (window as any).__WFS_MAP__.sources.map((s: any) => s.loaded))).toEqual([128, 512]);
    expect(requests.length).toBeGreaterThan(2);
    expect(requests.every(r => r.searchParams.get('source') === 'First' && r.searchParams.get('filter')?.includes('PropertyIsEqualTo'))).toBe(true);
    const before = requests.length;
    await page.evaluate(() => (window as any).__WFS_MAP__.workspace.select({ field: 'value', op: 'gte', value: '50' }, 'Value ≥ 50'));
    await expect(page.locator('#filterStatus')).toContainText('matches');
    expect(requests.length).toBe(before);
    await page.getByLabel('Server filter data source').selectOption('Second');
    await expect(page.getByLabel('Server rule 1 field', { exact: true })).toHaveCount(0);
    await page.getByLabel('Server filter data source').selectOption('First');
    await expect(page.getByLabel('Server rule 1 value', { exact: true })).toHaveValue('sensor');
    await page.screenshot({ path: 'test-results/server-filters-desktop.png', fullPage: true });
    await page.reload(); await ready(page);
    expect(await page.evaluate(() => (window as any).__WFS_MAP__.sources.map((s: any) => s.loaded))).toEqual([128, 512]);
    await openFilters(page);
    await page.getByText('Advanced server filters', { exact: true }).click();
    await page.getByRole('button', { name: 'Clear and reload source', exact: true }).click();
    await expect.poll(() => page.evaluate(() => (window as any).__WFS_MAP__.sources[0].loaded)).toBe(512); await ready(page);
});
test('CSV source rules pare ingestion and reload from original CSV while respecting text overrides and UTC dates', async ({ page }) => {
    const csv = { id: 'CSV', name: 'CSV', enabled: true, config: { ...defaultConfig, type: 'csv', longitudeField: 'lon', latitudeField: 'lat', timeField: 't', fieldTypes: '{"code":"string"}', csvText: 'lon,lat,code,value,t\n-1,54,001,1,2026-01-01T00:00:00Z\n-2,55,002,2,2026-01-01T01:00:00Z\n-3,56,001,3,2026-01-02T00:00:00Z' } };
    await seed(page, [csv]); await page.goto('/?time=all&autoload=1'); await ready(page);
    await openFilters(page);
    await page.getByText('Advanced server filters', { exact: true }).click();
    await page.getByRole('button', { name: 'Add server rule', exact: true }).click();
    await page.getByLabel('Server rule 1 field', { exact: true }).selectOption('code');
    await page.getByLabel('Server rule 1 value', { exact: true }).fill('001');
    await page.getByRole('button', { name: 'Add server rule', exact: true }).click();
    await page.getByLabel('Server rule 2 field', { exact: true }).selectOption('t');
    await page.getByLabel('Server rule 2 operator', { exact: true }).selectOption('gte');
    await page.getByLabel('Server rule 2 value', { exact: true }).fill('2026-01-02 00:00:00');
    await page.getByRole('button', { name: 'Apply and reload source', exact: true }).click();
    await expect.poll(() => page.evaluate(() => (window as any).__WFS_MAP__.sources[0].loaded)).toBe(1); await ready(page);
    expect(await page.evaluate(() => (window as any).__WFS_MAP__.sources[0].metrics.csvReport)).toMatchObject({ imported: 1, filtered: 2, rejected: 0 });
    expect(await page.evaluate(() => (window as any).__WFS_MAP__.sources[0].serverFilters[1].value)).toBe('2026-01-02T00:00:00.000Z');
    await page.getByRole('button', { name: 'Clear and reload source', exact: true }).click();
    await expect.poll(() => page.evaluate(() => (window as any).__WFS_MAP__.sources[0].loaded)).toBe(3); await ready(page);
});
test('field discovery is available before feature loading and unavailable saved fields block unbounded requests', async ({ page }) => {
    const s = { ...wfs('First'), serverFilters: [{ field: 'gone', kind: 'number', op: 'gt', value: '5' }] };
    await seed(page, [s]);
    let featureRequests = 0;
    page.on('request', r => { if (new URL(r.url()).searchParams.get('request') === 'GetFeature') featureRequests++; });
    await page.goto('/?time=all&autoload=1');
    await expect(page.locator('#status')).toContainText('missing or its type changed');
    expect(featureRequests).toBe(0);
    await openFilters(page);
    await page.getByText('Advanced server filters', { exact: true }).click();
    await expect(page.getByRole('button', { name: 'Read available fields', exact: true })).toBeEnabled();
    await expect.poll(() => page.getByLabel('Server rule 1 field', { exact: true }).locator('option').count()).toBeGreaterThan(1);
    await page.getByLabel('Server rule 1 field', { exact: true }).selectOption('value');
    await page.getByLabel('Server rule 1 value', { exact: true }).fill('10');
    await page.getByRole('button', { name: 'Apply and reload source', exact: true }).click(); await ready(page);
    expect(featureRequests).toBeGreaterThan(0);
});
test('empty load retains its schema, validates edits, and clearing restores data on mobile', async ({ page }) => {
    await page.setViewportSize({ width: 390, height: 844 });
    await seed(page, [{ ...wfs('First'), serverFilters: [{ field: 'value', kind: 'number', op: 'gt', value: '999' }] }]);
    await page.goto('/?time=all&autoload=1'); await ready(page);
    expect(await page.evaluate(() => (window as any).__WFS_MAP__.sources[0].loaded)).toBe(0);
    await openFilters(page);
    await page.getByText('Advanced server filters', { exact: true }).click();
    await page.getByLabel('Server rule 1 value', { exact: true }).fill('');
    await page.getByRole('button', { name: 'Apply and reload source', exact: true }).click();
    await expect(page.locator('#advancedServerFilters [role="alert"]')).toContainText('finite number');
    await page.screenshot({ path: 'test-results/server-filters-mobile.png', fullPage: true });
    await page.getByRole('button', { name: 'Clear and reload source', exact: true }).click();
    await expect.poll(() => page.evaluate(() => (window as any).__WFS_MAP__.sources[0].loaded)).toBe(512); await ready(page);
});
