import { test, expect } from '@playwright/test';
import { feature } from '../../server/demo.ts';
async function second(page: any, points = '2048') {
    await page.locator('#configLink').click();
    await page.locator('#addSource').click();
    await page.locator('#sourceName').fill('Second WFS');
    await page.locator('#url').fill(`/wfs?points=${points}&distribution=dense`);
    await page.locator('#layer').fill('demo:points');
    await page.locator('#updateSource').click();
    await page.locator('#saveSettings').click();
    await page.waitForFunction(() => { const s = (window as any).__WFS_MAP__.sources[1]; return s.done && s.metrics.analysisCharts?.length === 3; });
    await page.locator('#analysisLink').click();
}
test('two sources draw simultaneously, retain separate filters and chart settings, and re-enable without losing selections', async ({ page }) => {
    const errors: string[] = [];
    page.on('pageerror', e => errors.push(e.message));
    await page.goto('/?time=all&points=1024&autoload=1');
    await page.waitForFunction(() => (window as any).__WFS_MAP__?.metrics.analysisCharts);
    await second(page);
    await expect(page.locator('#hud')).toContainText('Loaded 3,072');
    await page.locator('.chart-card').first().getByRole('button', { name: 'Settings', exact: true }).click();
    await page.locator('.chart-card').first().getByLabel('Chart type').selectOption('pie');
    await page.evaluate(() => { const h = (window as any).__WFS_MAP__; h.filter([{ field: 'category', op: 'eq', value: 'sensor' }]); });
    await expect(page.locator('#filterStatus')).toContainText('256 matches');
    const ids = await page.evaluate(() => (window as any).__WFS_MAP__.sources.map((s: any) => s.id));
    await page.locator('#filterSource').selectOption(ids[1]);
    await expect(page.locator(`.chart-card[data-source-id="${ids[1]}"]`).first().getByLabel('Chart type')).toHaveValue('bar');
    await expect(page.locator('.chart-card')).toHaveCount(6);
    await page.evaluate(() => { const h = (window as any).__WFS_MAP__; h.workspace.select({ field: 'category', op: 'eq', value: 'vehicle' }, 'Vehicles'); });
    await expect(page.locator('#filterStatus')).toContainText('512 matches');
    await page.locator('#filterSource').selectOption(ids[0]);
    await expect(page.locator('.chart-card').first().getByLabel('Chart type')).toHaveValue('pie');
    await expect(page.locator('#filterStatus')).toContainText('256 matches');
    await expect(page.locator('#hud')).toHaveText('Loaded 3,072 points');
    expect(await page.evaluate(() => (window as any).__WFS_MAP__.sources.reduce((n: number, s: any) => n + s.selected, 0))).toBe(768);
    await page.locator('#configLink').click();
    await page.getByRole('checkbox', { name: 'Enable Second WFS', exact: true }).uncheck();
    await page.locator('#saveSettings').click();
    await page.locator('#analysisLink').click();
    await expect(page.locator('#hud')).toContainText('Loaded 1,024');
    const unloaded = await page.evaluate(() => { const s = (window as any).__WFS_MAP__.sources[1]; return { loaded: s.loaded, gpuBytes: s.layer.gpuBytes, worker: !!s.worker }; });
    expect(unloaded.loaded).toBe(0);
    expect(unloaded.gpuBytes).toBe(0);
    expect(unloaded.worker).toBe(false);
    await page.locator('#configLink').click();
    await page.getByRole('checkbox', { name: 'Enable Second WFS', exact: true }).check();
    await page.locator('#saveSettings').click();
    await page.waitForFunction(() => (window as any).__WFS_MAP__.sources[1].metrics.filterCount === 512);
    await page.locator('#analysisLink').click();
    await page.locator('#filterSource').selectOption(ids[1]);
    await expect(page.locator('#rules .selection').getByLabel('Filter value')).toHaveValue('vehicle');
    await expect(page.locator('#filterStatus')).toContainText('512 matches');
    expect(errors).toEqual([]);
});
test('overlapping IDs across sources pick the top rendered source with its own metadata', async ({ page }) => {
    await page.goto('/?time=all&points=1024&autoload=1');
    await page.waitForFunction(() => (window as any).__WFS_MAP__?.metrics.analysisCharts);
    await second(page, '1024');
    await page.evaluate(() => { const h = (window as any).__WFS_MAP__; for (const s of h.sources)
        h.filterSource(s.id, [{ field: 'id', op: 'eq', value: '48' }]); });
    await page.waitForFunction(() => (window as any).__WFS_MAP__.sources.every((s: any) => s.metrics.filterCount === 1));
    const f = feature(48, 'dense');
    await page.evaluate(c => (window as any).__WFS_MAP__.map.jumpTo({ center: c, zoom: 18 }), f.geometry.coordinates);
    await page.waitForFunction(() => (window as any).__WFS_MAP__.sources[1].layer.drawnLastFrame === 1);
    await page.locator('#map').scrollIntoViewIfNeeded();
    const p = await page.evaluate(c => { const m = (window as any).__WFS_MAP__.map, p = m.project(c), r = m.getCanvas().getBoundingClientRect(); return { x: p.x + r.x, y: p.y + r.y }; }, f.geometry.coordinates);
    await page.mouse.dblclick(p.x, p.y);
    await expect(page.locator('.metadata')).toContainText('Second WFS');
    await expect(page.locator('.metadata')).toContainText('points.48');
});
test('source lists persist and failure in one source leaves others available', async ({ page }) => {
    await page.goto('/?time=all&points=1024&autoload=1');
    await page.waitForFunction(() => (window as any).__WFS_MAP__?.metrics.analysisCharts);
    await page.locator('#configLink').click();
    await page.locator('#addSource').click();
    await page.locator('#sourceName').fill('Unavailable WFS');
    await page.locator('#url').fill('/not-a-wfs');
    await page.locator('#layer').fill('test:points');
    await page.locator('#updateSource').click();
    await page.locator('#saveSettings').click();
    await page.waitForFunction(() => (window as any).__WFS_MAP__.sources[1].error);
    await page.locator('#analysisLink').click();
    await expect(page.locator('#hud')).toContainText('Loaded 1,024');
    await expect(page.locator('.chart-card')).toHaveCount(3);
    await page.reload();
    await page.waitForFunction(() => (window as any).__WFS_MAP__?.metrics.analysisCharts);
    await expect(page.locator('#filterSource option')).toHaveCount(2);
    await page.locator('#configLink').click();
    await expect(page.getByRole('checkbox', { name: 'Enable Unavailable WFS', exact: true })).toBeChecked();
});
test('sources with different schemas expose only their own fields and counts', async ({ page }) => {
    const offsets: number[] = [];
    await page.route('**/alternate-wfs?*', async (route) => { const u = new URL(route.request().url()), operation = u.searchParams.get('request'); if (operation === 'DescribeFeatureType') {
        await route.fulfill({ status: 404, body: 'No schema' });
        return;
    } if (u.searchParams.get('resultType') === 'hits') {
        await route.fulfill({ contentType: 'application/xml', body: '<FeatureCollection numberMatched="2"/>' });
        return;
    }
    const offset = Number(u.searchParams.get('startIndex')), count = Number(u.searchParams.get('count'));
    offsets.push(offset);
    const features = [{ id: 'alternate.0', type: 'Feature', geometry: { type: 'Point', coordinates: [-1, 54] }, properties: { temperature: 7, name: 'north' } }, { id: 'alternate.1', type: 'Feature', geometry: { type: 'Point', coordinates: [-2, 53] }, properties: { temperature: 9, name: 'south' } }];
    await route.fulfill({ contentType: 'application/json', json: { type: 'FeatureCollection', numberMatched: 2, features: features.slice(offset, offset + count) } }); });
    await page.goto('/?time=all&points=1024&autoload=1');
    await page.waitForFunction(() => (window as any).__WFS_MAP__?.metrics.analysisCharts);
    await page.locator('#configLink').click();
    await page.locator('#addSource').click();
    await page.locator('#sourceName').fill('Other schema');
    await page.locator('#url').fill('/alternate-wfs');
    await page.locator('#layer').fill('test:points');
    await page.locator('#updateSource').click();
    await page.locator('#saveSettings').click();
    await page.waitForFunction(() => (window as any).__WFS_MAP__.sources[1].metrics.analysisCharts);
    expect(offsets).toEqual([0, 2]);
    await page.locator('#analysisLink').click();
    const id = await page.evaluate(() => (window as any).__WFS_MAP__.sources[1].id);
    await page.locator('#filterSource').selectOption(id);
    await page.locator('#rules > .filter-group > .group-head').getByRole('button', { name: '+ Rule', exact: true }).click();
    await expect(page.getByLabel('Attribute', {exact:true}).locator('option')).toHaveText(['temperature (number)', 'name (string)']);
    await page.getByLabel('Attribute', {exact:true}).selectOption('temperature');
    await page.getByLabel('Operator').selectOption('gte');
    await page.getByLabel('Filter value').fill('8');
    await page.locator('#apply').click();
    await expect(page.locator('#filterStatus')).toContainText('1 matches');
    expect(await page.evaluate(() => (window as any).__WFS_MAP__.sources[0].selected)).toBe(1024);
});
