{{- $db := .Values.externalDatabase -}}
{{- if not (and $db.existingSecret $db.existingSecretUrlKey) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-database" (include "wfs-map.fullname" .) | trunc 63 | trimSuffix "-" }}
  namespace: {{ include "wfs-map.namespace" . }}
  labels:
    {{- include "wfs-map.labels" . | nindent 4 }}
  {{- with mergeOverwrite (deepCopy .Values.commonAnnotations) $db.secretAnnotations }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  DATABASE_URL: {{ include "wfs-map.databaseUrl" . | b64enc | quote }}
  {{- if not $db.existingSecret }}
  PGPASSWORD: {{ $db.password | b64enc | quote }}
  {{- end }}
{{- end }}
